### ISSUE TITLE
Add `pyyaml` to the requirements

### ISSUE THREAD

**Issue by WoLpH** [bstriner/github-bot-close-inactive-issues#1]
On bare Python installations the app fails on `No module named 'yaml'`

PS: Awesome project, I'm just at the process of setting this up but it would be a tremendous help for me. I wish there was a service such as readthedocs/travis that took care of this.

**Comment by bstriner** [comment]
@WoLpH I'll add that to the setup. See the other issue for how to set it up on Travis. Nothing too complicated but maybe worth a blog or something. You need a dummy repository with 3 files and you need to be very careful to not enable automatic builds on travis.

Please let me know if you have any other issues with setting it up.

Cheers

**Comment by bstriner** [comment]
@WoLpH just came across probot/stale if you're still looking for a service that'll set things up automatically.

Otherwise, closing issue.

Cheers!

**Comment by wolph** [comment]
Looks good, I'll give it a try :)
